title: Revolutionizing Education
description: Reimagining the way historical events are taught through TikTok-powered learning.
theme: jekyll-theme-minimal

# Social links (optional)
github_username: aiagent443

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 